version: "3.8"
services:
  web-service:
    build:
      dockerfile: Dockerfile
      context: service
    ports:
      - "80:3000"

#  redis:
#    image: redis:7.2.4-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - data:/data
#    command: redis-server --save 60 1 --requirepass password
#
#volumes:
#  data:
