- name: Pull docker image
  ansible.builtin.command:
    cmd: docker pull {{ container_image }}
  register: pull_image

- name: Debug
  ansible.builtin.debug:
    var: pull_image

- name: Print redis_instance_ip
  ansible.builtin.debug:
    var: "{{ terraform_outputs.redis_instance_ip.value }}"

- name: Read service-account.json
  ansible.builtin.set_fact:
    service_account: "{{ lookup('ansible.builtin.file', '../service-account.json') | from_json }}"

- name: Debug
  ansible.builtin.debug:
    var: service_account

# - name: Create Service
#   ansible.builtin.template:
#     src: docker-service.j2
#     dest: /etc/systemd/system/{{ container_name }}.service
#     mode: "0644"
  # notify: Reload systemd
