- name: Pull docker image
  ansible.builtin.command:
    cmd: docker pull {{ container_image }}
  register: pull_image

- name: Save redis_instance_ip from localhost
  ansible.builtin.set_fact:
    redis_instance_ip: "{{ hostvars['localhost']['redis_instance_ip'] }}"
  when: redis_instance_ip is not defined

- name: Save service_account from localhost
  ansible.builtin.set_fact:
    service_account: "{{ hostvars['localhost']['service_account'] }}"
  when: service_account is not defined

- name: Create Service file
  ansible.builtin.template:
    src: docker-service.j2
    dest: /etc/systemd/system/{{ container_name }}.service
    mode: "0644"
  notify: Restart Service
