- name: Deploy resources to google cloud
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read service-account.json
      ansible.builtin.set_fact:
        service_account: "{{ lookup('ansible.builtin.file', '../service-account.json') | from_json }}"

    - name: Get current username
      local_action: command whoami
      register: username

    - name: Apply the terraform configuration
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../terraform"
        state: present
        variables:
          project_id: "{{ service_account.project_id }}"
          user: "{{ username.stdout }}"
      register: deployed_tf
    
    - name: Save redis_instance_ip
      ansible.builtin.set_fact:
        redis_instance_ip: "{{ deployed_tf.outputs.redis_instance_ip.value }}"

    - name: Save host_vm_ips
      ansible.builtin.set_fact:
        host_vm_ips: "{{ deployed_tf.outputs.host_vm_ips.value }}"

    - name: Save load_balancer_ip
      ansible.builtin.set_fact:
        load_balancer_ip: "{{ deployed_tf.outputs.load_balancer_ip.value }}"

    - name: Add host_vm_ips to inventory
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        groups: host-vm
      with_items: "{{ host_vm_ips }}"
 
- name: Install dependencies to vm instance
  hosts: host-vm
  become: true
  tasks:
    - ansible.builtin.include_tasks:
        file: tasks/dependencies.yml

- name: Deploy the application
  hosts: host-vm
  become: true
  vars:
    container_name: image_text_extraction
    container_image: ghcr.io/tomvoet/{{ container_name }}:latest
  tasks:
    - ansible.builtin.include_tasks:
       file: tasks/deployment.yml
  handlers:
    - name: Restart Service
      ansible.builtin.systemd:
        name: "{{ container_name }}"
        state: restarted

- name: Print the load balancer IP
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: "The load balancer IP is {{ load_balancer_ip }}"
